spring:
  datasource:
    url: jdbc:mysql://localhost:3306/medicalDB
    username: user
    password: expresso

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
